# Generated by Django 2.2 on 2021-08-20 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('date', models.DateTimeField()),
                ('address', models.TextField(max_length=300)),
                ('type', models.TextField(max_length=300)),
                ('buyIn', models.IntegerField()),
                ('blinds', models.TextField()),
                ('numberOfPlayers', models.IntegerField()),
                ('desc', models.TextField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostedGames', to='login.User')),
                ('players', models.ManyToManyField(related_name='joinedGames', to='login.User')),
            ],
        ),
    ]
